device: "/dev/video2"
width: 1280
height: 720
fps: 30
flip_method: 0         # nvargus flip; ignored for V4L2
use_gstreamer: false
fourcc: "MJPG"
gstreamer_kwargs:
  sensor_id: 1
  sensor_mode: 3
  capture_width: 1280
  capture_height: 720
  display_width: 1280
  display_height: 720
  framerate: 30
